server:
  shutdown: graceful
  port: ${SERVER_PORT}

spring:
  application:
    name: gmuwiki
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://localhost:3306/my_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Esperer123!}
    pool:
      max-size: 100
      validation-query: SELECT 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: ${sql.show}
    properties:
      hibernate:
        format_sql: ${sql.format}
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 20s
